#!/bin/bash
# VPS Setup Script Generated by Solite
# ------------------------------------
# This script will automatically:
# 1. Update system packages
# 2. Install selected software
# 3. Configure basic security
# ------------------------------------

set -e # Exit on error

mkdir -p /var/azuracast
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
chmod a+x docker.sh
yes '' | ./docker.sh install
