#!/bin/bash
# VPS Setup Script Generated by Solite
# ------------------------------------
# This script will automatically:
# 1. Update system packages
# 2. Install selected software
# 3. Configure basic security
# ------------------------------------

set -e # Exit on error

echo ">>> Starting System Update..."
apt-get update && apt-get upgrade -y
apt-get install -y curl wget git unzip htop

echo ">>> Installing Docker & Docker Compose..."
apt-get install -y ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

echo   "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |   tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl enable docker
echo "Docker installed successfully."

echo ">>> Installing Nginx..."
apt-get install -y nginx
systemctl enable nginx
systemctl start nginx
# Allow Nginx through firewall if installed later

echo ">>> Configuring UFW Firewall..."
apt-get install -y ufw
# Set defaults
ufw default deny incoming
ufw default allow outgoing
# Allow SSH (Important!)
ufw allow ssh
ufw allow 22
# Allow HTTP/HTTPS
ufw allow 80/tcp
ufw allow 443/tcp
echo "y" | ufw enable
echo "Firewall configured."

echo ">>> Setting up 1GB Swap File..."
fallocate -l 1G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=1024
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo '/swapfile none swap sw 0 0' >> /etc/fstab
echo "Swap file created."

echo ">>> Setup Complete. Rebooting in 5 seconds..."
sleep 5
reboot

echo ">>> Setup Complete! restart session or reboot may be required."
